include:
  - local: .kb-ci.yml

workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - when: never

stages:
  - verify
  - build
  - deploy

variables:
  NPM_REGISTRY: https://registry.npmmirror.com

verify_build:
  tags: 
    - crazy-team-ci
  stage: verify
  image: uhub.service.ucloud.cn/ai-mas-public/node:22-bookworm-slim
  before_script:
    - npm config set registry "${NPM_REGISTRY}"
  script:
    - npm ci
    - npm run build

build_image:
  stage: build
  extends:
    - .buildkit_image
