server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location = /lxy-training {
        return 301 /lxy-training/;
    }

    location /lxy-training/assets/ {
        alias /usr/share/nginx/html/assets/;
        try_files $uri =404;
    }

    location /lxy-training/ {
        rewrite ^/lxy-training/(.*)$ /$1 break;
        try_files $uri $uri/ /index.html;
    }
}
